-- MySQL Script generated by MySQL Workbench
-- Mon Sep 27 09:50:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema javaschool
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `javaschool` ;

-- -----------------------------------------------------
-- Schema javaschool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `javaschool` DEFAULT CHARACTER SET utf8 ;
USE `javaschool` ;

-- -----------------------------------------------------
-- Table `javaschool`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`options` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `connection_price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`tariff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`tariff` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`tariff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`address` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `house` INT NOT NULL,
  `building` VARCHAR(45) NULL,
  `apartment` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`users` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_id` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `passport` int NULL,
  `email` VARCHAR(45) NOT NULL unique,
  `birth_date` DATE NULL,
  `password` VARCHAR(45) NOT NULL,
  `enabled` TINYINT DEFAULT 1 NOT NULL,
  `authority` VARCHAR(45) DEFAULT 'ROLE_USER' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `check_users_enabled` check (`enabled`=0 or `enabled` =1),
  CONSTRAINT `check_users_authority` check (`authority`='ROLE_USER' or `authority` ='ROLE_ADMIN'),
  CONSTRAINT `fk_users_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `javaschool`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`contract` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`contract` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tariff_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `phone_number` BIGINT NOT NULL,
  `enabled` TINYINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contract_tariff1_idx` (`tariff_id` ASC) VISIBLE,
  INDEX `fk_contract_users1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  CONSTRAINT `check_contract_enabled` check (`enabled`=0 or `enabled` =1),
  CONSTRAINT `fk_contract_tariff1`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `javaschool`.`tariff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `javaschool`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`tariff_options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`tariff-options` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`tariff_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tariff_id` INT NOT NULL,
  `option_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tariff_options_tariff1_idx` (`tariff_id` ASC) VISIBLE,
  INDEX `fk_tariff_options_options_idx` (`option_id` ASC) VISIBLE,
  UNIQUE INDEX `tariff_id_options_id_UNIQUE` (`tariff_id` ASC, `option_id` ASC) VISIBLE,
  CONSTRAINT `fk_options_has_tariff_options1`
    FOREIGN KEY (`option_id`)
    REFERENCES `javaschool`.`options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_options_has_tariff_tariff1`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `javaschool`.`tariff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`contract_tariff_options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`contract_tariff_options` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`contract_tariff_options` (
  `contract_id` INT NOT NULL,
  `tariff_options_id` INT NOT NULL,
  PRIMARY KEY (`contract_id`, `tariff_options_id`),
  INDEX `fk_contract_tariff_options_tariff_options1_idx` (`tariff_options_id` ASC) VISIBLE,
  INDEX `fk_contract_tariff_options_contract1_idx` (`contract_id` ASC) VISIBLE,  
  CONSTRAINT `fk_contract_has_tariff_options_contract1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `javaschool`.`contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_has_tariff_options_tariff_options1`
    FOREIGN KEY (`tariff_options_id`)
    REFERENCES `javaschool`.`tariff_options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
