-- MySQL Script generated by MySQL Workbench
-- Mon Sep 27 09:50:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema javaschool
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `javaschool` ;

-- -----------------------------------------------------
-- Schema javaschool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `javaschool` DEFAULT CHARACTER SET utf8 ;
USE `javaschool` ;

-- -----------------------------------------------------
-- Table `javaschool`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`options` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`options` (
  `optionId` INT NOT NULL AUTO_INCREMENT,
  `optionName` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `connectionPrice` INT NOT NULL,
  PRIMARY KEY (`optionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`tariff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`tariff` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`tariff` (
  `tariffId` INT NOT NULL AUTO_INCREMENT,
  `tariffName` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`tariffId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`address` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`address` (
  `addressId` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `house` INT NOT NULL,
  `building` VARCHAR(45) NULL,
  `apartment` INT NULL,
  PRIMARY KEY (`addressId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`client` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`client` (
  `clientId` INT NOT NULL AUTO_INCREMENT,
  `addressId` INT NOT NULL,
  `clientName` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `passport` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `birthDate` DATE NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `isBlocked` TINYINT DEFAULT 0 NOT NULL,
  PRIMARY KEY (`clientId`),
  INDEX `fk_client_address1_idx` (`addressId` ASC) VISIBLE,
  CONSTRAINT `checkClientIsBlocked` check (`isBlocked`=0 or `isBlocked` =1),
  CONSTRAINT `fk_client_address1`
    FOREIGN KEY (`addressId`)
    REFERENCES `javaschool`.`address` (`addressId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`contract` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`contract` (
  `contractId` INT NOT NULL AUTO_INCREMENT,
  `tariffId` INT NOT NULL,
  `clientId` INT NOT NULL,
  `phoneNumber` BIGINT NOT NULL,
  `isBlocked` TINYINT DEFAULT 0 NOT NULL,
  PRIMARY KEY (`contractId`),
  INDEX `fk_contract_tariff1_idx` (`tariffId` ASC) VISIBLE,
  INDEX `fk_contract_client1_idx` (`clientId` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phoneNumber` ASC) VISIBLE,
  CONSTRAINT `checkContractIsBlocked` check (`isBlocked`=0 or `isBlocked` =1),
  CONSTRAINT `fk_contract_tariff1`
    FOREIGN KEY (`tariffId`)
    REFERENCES `javaschool`.`tariff` (`tariffId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_client1`
    FOREIGN KEY (`clientId`)
    REFERENCES `javaschool`.`client` (`clientId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`tariffOptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`tariffOptions` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`tariffOptions` (
  `tariffOptionsId` INT NOT NULL AUTO_INCREMENT,
  `tariffId` INT NOT NULL,
  `optionId` INT NOT NULL,
  PRIMARY KEY (`tariffOptionsId`),
  INDEX `fk_tariff_options_tariff1_idx` (`tariffId` ASC) VISIBLE,
  INDEX `fk_tariff_options_options_idx` (`optionId` ASC) VISIBLE,
  UNIQUE INDEX `tariff_id_options_id_UNIQUE` (`tariffId` ASC, `optionId` ASC) VISIBLE,
  CONSTRAINT `fk_options_has_tariff_options1`
    FOREIGN KEY (`optionId`)
    REFERENCES `javaschool`.`options` (`optionId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_options_has_tariff_tariff1`
    FOREIGN KEY (`tariffId`)
    REFERENCES `javaschool`.`tariff` (`tariffId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `javaschool`.`contractTariffOptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `javaschool`.`contractTariffOptions` ;

CREATE TABLE IF NOT EXISTS `javaschool`.`contractTariffOptions` (
  `contractId` INT NOT NULL,
  `tariffOptionsId` INT NOT NULL,
  PRIMARY KEY (`contractId`, `tariffOptionsId`),
  INDEX `fk_contract_tariff_options_tariff_options1_idx` (`tariffOptionsId` ASC) VISIBLE,
  INDEX `fk_contract_tariff_options_contract1_idx` (`contractId` ASC) VISIBLE,  
  CONSTRAINT `fk_contract_has_tariff_options_contract1`
    FOREIGN KEY (`contractId`)
    REFERENCES `javaschool`.`contract` (`contractId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contract_has_tariff_options_tariff_options1`
    FOREIGN KEY (`tariffOptionsId`)
    REFERENCES `javaschool`.`tariffOptions` (`tariffOptionsId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
